# Generated by Django 3.2.7 on 2021-12-18 05:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cart', '0001_initial'),
        ('shopping', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userorder',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ordertotal',
            name='products',
            field=models.ManyToManyField(to='cart.Order'),
        ),
        migrations.AddField(
            model_name='ordertotal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.userorder'),
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shopping.products'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.userorder'),
        ),
    ]
